name: "PR Review Apps on fly.io"
description: "Deploy temporary apps from pull requests on Fly.io"
author: Fly
branding:
  icon: "upload-cloud"
  color: "purple"
runs:
  using: "docker"
  image: "Dockerfile"
inputs:
  app:
    description: Fly app name (alternatively, set the env FLY_APP)
  image:
    description: Optional pre-existing Docker image to use
  config:
    description: Optional path to a custom Fly toml config. Config path should be relative to `path` parameter, if specified.
  region:
    description: Region to launch the app in (alternatively, set the env FLY_REGION)
  org:
    description: Organization to launch the app in (alternatively, set the env FLY_ORG)
  path:
    description: path to a directory containing a fly.toml to clone
  postgres:
    description: Optionally attach the app to a pre-existing Postgres cluster on Fly
  update:
    description: Whether new commits to the PR should re-deploy the Fly app
    default: true
  secrets:
    description: White space separated secrets to be set on the app.
  args:
    description: White space separated build arguments to be set during deployment.
  vm:
    description: VM named size (defaults to shared-cpu-1x).
  ha:
    description: Boolean expressing the application needs to be highly available (default is false).